services:
  neverland-field-controller:
    image: carollokyi/neverland-field-controller:assessment
    ports:
      - "502:502"
    command: ["python", "app_assessment.py"]

  neverland-operator-console:
    profiles: ["disabled"]
