services:
  neverland-field-controller:
    image: carollokyi/neverland-field-controller:teaching
    ports:
      - "1502:502"

  neverland-operator-console:
    image: carollokyi/neverland-operator-console:teaching
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - MODBUS_HOST=neverland-field-controller
      - MODBUS_PORT=502
      - MODBUS_SLAVE_ID=1
